# Site settings
title: "js-colors"
email: "ryan.null@gmail.com"
description: > # this means to ignore newlines until "baseurl:"
  Color manipulation written in javascript that allows you to update and mess with colors on the fly.  It can also do conversion, calculation, mixing, and much more!
baseurl: "/js-colors" # the subpath of your site, e.g. /blog/
url: "http://bigjuevos.github.io" # the base hostname & protocol for your site
twitter_username: BIGjuevos
github_username:  BIGjuevos

# Build settings
markdown: kramdown
